"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.version = void 0;
// Generated by genversion.
exports.version = '0.1.0-alpha.3';
//# sourceMappingURL=version.js.map